---
- name: Transfer and execute a script.
  hosts: stage
  become: yes
  tasks:
     - name: Remove a file, if present
       file:
        path: /opt/anand_profile 
        state: absent
       
     - name: Creates directory
       file:
        path: /opt/anand_profile
        state: directory
        owner: root
        group: root
        mode: 0775
        recurse: yes

     - name: Ansible copy directory to the remote server
       copy:
        src=inventory
        dest=/opt/anand_profile

     - name: Ensure directories are 0775
       file: dest=/opt/anand_profile/deploy.sh owner=root group=root mode=0755 recurse=yes

     - name: Execute the script
       shell: /opt/entmon-email-service/deploy.sh "{{repo_name}}" "{{dockerImage}}" "{{dockerimagerepo}}"





